services:
  api:
    build: .
    container_name: school-activities-api
    restart: always
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: school-activities-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
